### ISSUE TITLE
Unmap all then map again failure

### ISSUE THREAD

**Issue by svalat** [sergiorg-kth/ummap-io#1]
If we unmap all segments managed by uMMAP-IO then map again the library tries to init itself again but fail on a condition in `configure_pf_handler` on check of `g_status.r_index`.

**Comment by sergiorg-hpc** [comment]
@svalat I created a new branch [`sergiorg_initfix`](/sergiorg-kth/ummap-io/tree/sergiorg_initfix) that tries to fix this issue, as well as the need to require a "start-up" method for uMMAP-IO. I have not tested it thoroughly yet, but in theory the changes should work (except for one edge case, but it is minor).

I will provide more details as soon as I have done some testing.

**Comment by sergiorg-hpc** [comment]
See "Initialization and re-configure support fix" #2

**Comment by sergiorg-hpc** [comment]
**Important:** Don’t forget to update the `umalloc` repository after pushing to the `master` branch.

**Comment by sergiorg-hpc** [comment]
The changes have been merged into the `master` branch.
